Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/millennium_hardware?createDatabaseIfNotExist=TRUE
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true